---
title: "Class 11"
author: "Sandy Schweis"
date: "5/7/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## The PDB database

The [PDB](http://www.rcsb.org/) is the main repository for biomolecular structure data. 

Here we examine contents of the PDB:

```{r}
db <- read.csv("Data Export Summary.csv", row.names = 1)
head(db)
```

How many are xray?
```{r}
(db$Total/sum(db$Total)) *100
```


#What proportion of structures are protein
```{r}
(sum(db$Proteins)/sum(db$Total)) * 100
```

```{r}
library(datapasta)


tmp <- data.frame(stringsAsFactors=FALSE,
   Experimental.Method = c("X-Ray", "NMR", "Electron Microscopy", "Other",
                           "Multi Method", "Total"),
              Proteins = c(126880, 11062, 2277, 256, 129, 140604),
         Nucleic.Acids = c(2012, 1279, 31, 4, 5, 3331),
    ProteinComplex = c(6547, 259, 800, 6, 2, 7614),
                 Other = c(8, 8, 0, 13, 1, 30),
                 Total = c(135447, 12608, 3108, 279, 137, 151579)
)

```

> Q2: Type HIV in the PDB website search box on the home page and determine how many
HIV-1 protease structures are in the current PDB?

There are 1157 as of 2019-05-07


##Section 3

```{r}
library(bio3d)

pdb <- read.pdb("1hsg.pdb")
pdb
```

```{r}
attributes(pdb)
```

```{r}
head(pdb$atom)
```

```{r}
atom.select(pdb, "protein")
```

```{r}
prot.pdb <- atom.select(pdb, "protein", value = TRUE)
write.pdb(prot.pdb, file = "1hsg_protein.pdb")
```

```{r}
lig.pdb <- atom.select(pdb, "ligand", value = TRUE)
write.pdb(lig.pdb, file = "1hsg_ligand.pdb")
```

```{r}
pdb$atom[1:2, c("eleno", "elety", "x","y","z")]
pdb$atom$elety[1:2]
plot.bio3d(pdb$atom$b[pdb$calpha], sse=pdb, typ="l", ylab= "B factor" )
```

```{r}
str(pdb$atom)
```

## Section 5
```{r}
aa <- get.seq("1ake_A")
b <- blast.pdb(aa)
```
```{r}
hits <- plot(b)
```

```{r}
head(hits$pdb.id)
```

```{r}
files <- get.pdb(hits$pdb.id, path="pdbs", split=TRUE, gzip=TRUE)
```

```{r}
pdbs <- pdbaln(files)
```

```{r}
ids <- basename.pdb(pdbs$id)
plot(pdbs, labels=ids)
```

```{r}
# Calculate sequence conservation
cons <- conserv(pdbs, method="entropy22")
# SSE annotations
sse <- pdbs2sse(pdbs, ind=1, rm.gaps=FALSE)
# Plot conservation per residue
plotb3(cons, sse=sse, ylab="Sequence entropy")
```

```{r}
anno <- pdb.annotate(ids)
print(unique(anno$source))

```




















