---
title: 'Class 6: R Functions'
author: "Sandy Schweis"
date: "4/18/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### About
This is my **class 6** R markdown document with my *code* and notes for the day.

```{r}
plot(1:10, typ="l", col="pink")
```

## Reading in files practice

There are 3 files to read.

```{r}
read.table("test1.txt", header = TRUE, sep=",")
```
```{r}
read.table("test2.txt", header = TRUE, sep = "$")
```
```{r}
read.table("test3.txt")
```

## Functions

Our first silly function example:
```{r}
add <- function(x, y=1) {
  # The body!!!
  x + y
}
```

```{r}
add(10)
```

```{r}
add(10, 10)
```

```{r}
#add(x=1, y="b")
```


```{r}
#rescale( c(1,10,"string") )
```

```{r}
rescale <- function(x) {
 rng <-range(x, na.rm=TRUE)
 (x - rng[1]) / (rng[2] - rng[1])
}

```

```{r}
x <- c(1, 2, 3, NA, 10)
range(x, na.rm= TRUE)
rescale(c(1,2,NA,3,10))
```



```{r}
rescale <- function(x) {
 rng <-range(x, na.rm=TRUE)
 (x - rng[1]) / (rng[2] - rng[1])
}

```

```{r}
rescale(1:10)
```

```{r}
rescale2 <- function(x, na.rm=TRUE) {
 rng <-range(x, na.rm=na.rm)
 (x - rng[1]) / (rng[2] - rng[1])
}
```

```{r}
rescale2(c(1,3,NA,10))
```



```{r}
rescale3 <- function(x, na.rm=TRUE, plot=FALSE) {
 rng <-range(x, na.rm=na.rm)
 print("Hello")
 answer <- (x - rng[1]) / (rng[2] - rng[1])
 print("is it me you are looking for?")
 if(plot) {
 plot(answer, typ="b", lwd=4)
 }
 print("I can see it in ...")
 return(answer)
}
```

```{r}
rescale3( c(1, 3, NA, 10))
```

```{r}
rescale3( c(1,3,NA,10), plot = TRUE)
```


